# Generated by Django 3.1.1 on 2021-02-04 00:44

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('address_string', models.CharField(db_column='address_string', max_length=100)),
                ('created_date', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=40)),
                ('reference', models.CharField(db_column='reference', max_length=80)),
                ('created_date', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('phone_number', models.CharField(db_column='phone_number', default=None, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+987654321000'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_by', models.ForeignKey(db_column='created_by', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', default='inactive', max_length=30)),
                ('paid_amount', models.IntegerField(db_column='paid_amount', default=0)),
                ('active_date', models.DateTimeField(db_column='active_date', default=None, null=True)),
                ('created_date', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(db_column='expiry_date', default=datetime.datetime(2021, 2, 14, 0, 44, 13, 770934, tzinfo=utc))),
                ('purchase_order_number', models.IntegerField(db_column='purchase_order_number', default=0)),
                ('payment_term', models.CharField(db_column='payment_term', max_length=30, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='user_dashboards.customer')),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('price', models.IntegerField(db_column='price', default=0)),
                ('unit', models.CharField(db_column='unit', default='kilograms', max_length=30)),
                ('discount', models.IntegerField(db_column='discount', default=0, null=True)),
                ('created_date', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddresses',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('address', models.ForeignKey(db_column='address', on_delete=django.db.models.deletion.CASCADE, to='user_dashboards.address')),
                ('customer', models.ForeignKey(db_column='customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='user_dashboards.customer')),
            ],
            options={
                'db_table': 'customer_addresses',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='quantity', default=0)),
                ('created_date', models.DateTimeField(db_column='created_date', default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='user_dashboards.product')),
                ('receipt_id', models.ForeignKey(db_column='receipt_id', on_delete=django.db.models.deletion.CASCADE, to='user_dashboards.receipt')),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
